# Site settings
baseurl = "https://bzinoun.github.io/socrates-ma/"
languageCode = "en-us"
title = "SoCraTes-MA"
description = "International Conference for Software Craft and Testing"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "278882533"


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "SoCraTes Maroc"
	description = "International Conference for Software Craft and Testing"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
	#
	# What you need to do for the setup?
	#
	# - set your email address under 'email' below
	# - upload the generated site to your server
	# - send a dummy email yourself to confirm your account
	# - click the confirm link in the email from www.formspree.io
	# - you're done. Happy mailing!
	email = "socrates.ma@gmail.com"
	gforms = "1FAIpQLSc40jBL3dTrDNw_efqMEgsFuLRSrP09Ry2mm8n_z52Vmk_s0w/"

	# Navigation
	[params.navigation]
		brand = "SoCraTes Maroc"
		services = "What is it?"
		portfolio = "Information"
		about = "History"
		team = "Family"
		contact = "Registration"
		partners = "Partners"
		sponsors = "Sponsors"

	# Add custom links. Those can be pre- and postpended to the default menu above.
	# Use the weight attribute to order your custom links. Uncomment the example
	# below and replace the values with your own.

	# prepended links
	#[[menu.prepend]]
	#    url = "http://gohugo.io"
	#    name = "Hugo"
	#    weight = 10

	# postpended links
	[[menu.postpend]]
		url = "https://github.com/SoCraTes-MA/socrates-ma.github.io/wiki"
		name = "Wiki"

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "September 12-15, 2024 International Conference for Software Craft and Testing."
		subtitle = "SoCraTeS Morocco 2024"
		buttontext = "Tell me more"

	# Services section
	[params.services]
		enable = true
		title = "What it is about?"
		subtitle = "This event is about the sustainable creation of useful software in a responsible way."

		[[params.services.row]]

			[[params.services.row.list]]
				icon = "fa-users"
				title = "It's about People"
				description = "Everyone who is concerned with coding, testing, code quality and craft."

			[[params.services.row.list]]
				icon = "fa-play-circle"
				title = "It's about Action"
				description = "The event will be run as a non-profit, low-cost event. It will be much like a retreat. We will be there for 48 hours to collaborate and share ideas."

			[[params.services.row.list]]
				icon = "fa-plus-circle"
				title = "It's about Fun"
				description = "We will not only spend the days together but also the nights. And – believe it or not – programmers are a great company! There will be be lots of opportunities to spend your time. Starting with simple chilling over hiking and biking, playing games, hanging around, talking, laughing, …"

	# Portfolio section
	[params.portfolio]
		enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Information"
		subtitle = "Information"

		[params.portfolio.modal]
			client = "Client"
			date = "Date"
			category = "Category"
			buttontext = "Close"

	# About section
	[params.about]
		enable = true
		title = "History"
		subtitle = "Previous and next edition."
		endpoint = "Be part<br>of the<br>event!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.

		[[params.about.events]]
			img = "vechy-bouznika.jpg"
			date = "September 12-15, 2024"
			title = "Third edition - Bouznika"
			description = "We plan to gather 60 software crafts, join us and be part of this edition!"

		[[params.about.events]]
			img = "vechy-bouznika.jpg"
			date = "March 10-12, 2023"
			title = "Second edition - Bouznika"
			description = "We gathered 45 software craft and 10 partner/sponsors"

      	[[params.about.events]]
			img = "ronsard.jpg"
			date = "March 25-27, 2022"
			title = "First edition - Marrakesh"
			description = "We gathered 30 software craft and 8 partner/sponsors"




	# Team section
	[params.team]
		enable = true
		title = "SoCraTes-MA is a part of a big family."
		subtitle = "The first “Software Craft and Testing (un)conference” took place a few years ago in Germany and is organised every year since 2011."
		description = "Other conferences have emerged in other European countries such as SoCraTes UK SoCraTes FR and SoCraTes Canaries."


		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "SoCraTes_FR.png"
			name = "SoCraTes FR"
			position = "France"
			social = [
				["fa-twitter", "https://twitter.com/#socratesfr"],
				["fa-link", "https://socrates-fr.github.io"]
			]

		[[params.team.members]]
			img = "SoCraTes.png"
			name = "SoCraTes"
			position = "Germany"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_Conf"],
				["fa-link", "https://www.socrates-conference.de"]
			]

		[[params.team.members]]
			img = "SoCraTes_UK.png"
			name = "SoCraTes UK"
			position = "United Kingdom"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_UK"],
				["fa-link", "http://socratesuk.org"]
			]

		[[params.team.members]]
			img = "SoCraTes_ES.png"
			name = "SoCraTes Canaries"
			position = "Spain"
			social = [
				["fa-twitter", "https://twitter.com/socracan"],
				["fa-link", "https://www.socracan.com/"]
			]

		[[params.team.members]]
			img = "SoCraTes_CH.jpeg"
			name = "SoCraTes Conf Switzerland"
			position = "Switzerland"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_CH"],
				["fa-link", "http://socrates-ch.org"]
			]

		[[params.team.members]]
			img = "SoCraTesDay_CH.jpeg"
			name = "SoCraTes Day Switzerland"
			position = "Switzerland"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTesDay_CH"],
				["fa-link", "http://socrates-day.ch"]
			]

		[[params.team.members]]
			img = "SoCraTes_BE.png"
			name = "SoCraTes BE"
			position = "Belgium"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_BE"],
				["fa-link", "http://socratesbe.org"]
			]

		[[params.team.members]]
			img = "SoCraTes_IT.png"
			name = "SoCraTes IT"
			position = "Italy"
			social = [
				["fa-twitter", "https://twitter.com/SoCraTes_Italy"],
				["fa-link", "http://www.socrates-conference.it"]
			]

		[[params.team.members]]
			img = "CodeFreeze.png"
			name = "CodeFreeze"
			position = "Finland"
			social = [
				["fa-twitter", "https://twitter.com/codefreeze_fi"],
				["fa-link", "http://www.codefreeze.fi"]
			]

		[[params.team.members]]
			img = "ITAKE.png"
			name = "I T.A.K.E. Unconference"
			position = "Romania"
			social = [
				["fa-twitter", "https://twitter.com/itakeunconf"],
				["fa-link", "http://itakeunconf.com"]
			]

		[[params.team.members]]
			img = "agileCrete.png"
			name = "AgileCrete Unconference"
			position = "Crete, Greece"
			social = [
				["fa-twitter", "https://twitter.com/AgileCrete"],
				["fa-link", "https://agilecrete.org"]
			]

	# Partners section
	[params.partners]
		enable = true
		title = "Our Knowledge Partner"
		subtitle = ""

		[[params.partner]]
			name = "McKinsey & Company"
			logo = "mckinsey-logo.png"
			link = "https://www.mckinsey.com/"

	# Sponsor section
	[params.sponsors]
		enable = true
		title = "Our Previous Sponsors"
		subtitle = ""

		[[params.sponsor]]
			name = "Societe Generale ATS"
			logo = "SG-ATS.jpg"
			link = "https://careers.societegenerale.com/en/group/africa-technologies-services"

   		[[params.sponsor]]
			name = "Keiken Digital Solutions"
			logo = "KEIKEN-LOGO.jpeg"
			link = "https://keiken-digital.com/"
    
   		[[params.sponsor]]
			name = "Maltem Africa"
			logo = "maltem-square.jpeg"
			link = "https://maltem.com/en/blog/portfolio-item/maltem-africa/"

		[[params.sponsor]]
		 	name = "Zenika"
		 	logo = "logo-zenika.jpeg"
		 	link = "http://www.zenika.com"

		[[params.sponsor]]
			name = "INWI"
			logo = "inwi-square.jpeg"
			link = "https://inwi.ma/"

		[[params.sponsor]]
			name = "NimbleWays"
			logo = "nimble-square.jpeg"
			link = "https://www.nimbleways.com"

 		[[params.sponsor]]
			name = "Gemography"
			logo = "gemography-square.png"
			link = "https://www.gemography.com"

		[[params.sponsor]]
			name = "ZSoft Consulting"
			logo = "zsoft-logo.jpeg"
			link = "https://www.zsoft-consulting.com/"

		[[params.sponsor]]
		 	name = "Axa Maroc"
		 	logo = "axa-square.jpg"
		 	link = "https://www.axa.ma"

		[[params.sponsor]]
		 	name = "La Combe du Lion Vert"
		 	logo = "La_Combe_du_Lion_Vert.png"
		 	link = "https://la-combe-du-lion-vert.fr/"

		#[[params.sponsor]]
		#	name = "Octo Technology"
		#	logo = "octo-square.png"
		#	link = "http://www.octo.com"

 		#[[params.sponsor]]
 		#		name = "SOAT"
 		#		logo = "soat-square.png"
 		#		link = "http://www.soat.fr"

		#[[params.sponsor]]
		#	name = "Shodo"
		#	logo = "shodo-square.png"
		#	link = "https://shodo.io"

		#[[params.sponsor]]
 		# 		name = "Aneo"
 		# 		logo = "aneo-square.jpg"
 		# 		link = "http://www.aneo.eu"

		# [[params.sponsor]]
		# 	name = "Novencia"
		# 	logo = "novencia-square.jpg"
		# 	link = "http://www.novencia.com"
		
		


		# [[params.sponsor]]
        #	name = "BCG Platinion"
        #	logo = "bcg-square.png"
        #	link = "https://www.bcg.com/"

# 		[[params.sponsor]]
# 			name = "Viseo Technologies"
# 			logo = "viseo-square.jpg"
# 			link = "http://www.viseo.com"

# 		[[params.sponsor]]
# 			name = "Codurance"
# 			logo = "codurance-square.png"
# 			link = "http://codurance.com"

 		# [[params.sponsor]]
 		# 	name = "Orange"
 		# 	logo = "orange-square.png"
 		# 	link = "https://developer.orange.com"


	[params.socratesday]
		enable = false
		title = "Sponsorship"
		subtitle = ""
		description = "SoCraTes Day is an International Conference for Software Craft and Testing, a single-day version of the full SoCraTes Conferences. It provides an ideal setting for speaking to and coding with other talented and engaged developers, letting us learn from and with each other."

	[params.contact]
		enable = true
		title = "Pre-registration is now open !!"
		subtitle  = "The event will be limited to 40 participants with a managed hotel accomodation within Vichy Celestins, \n\n Please mind filling the form with your details, we will reach out and eventually confirm your seat"
		buttonText = "Send message"

	# Footer section
	[params.footer]
		enable = true
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/SoCraTes_MA/"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://www.linkedin.com/company/moroccansoftwarecrafters/"

    [[params.footer.social]]
			icon = "fa-instagram"
			link = "https://www.instagram.com/moroccansoftwarecrafters/"

